import mongoose, { Schema, Document, Model } from 'mongoose';

export interface IOrderItem {
  productId: string;
  name: string;
  price: number;
  quantity: number;
  image: string;
  variant?: string;
}

interface IStatusEvent {
  status: string;
  note?: string;
  at: Date;
}

export interface IOrder extends Document {
  userId: string;
  orderNumber: string;
  items: IOrderItem[];
  subtotal: number;
  gst: number;
  shippingCost: number;
  total: number;
  
  // Delivery Address
  deliveryAddress: {
    name: string;
    line1: string;
    line2?: string;
    city: string;
    state: string;
    pincode: string;
  };
  
  // Payment Info
  paymentMethod: 'cod' | 'card' | 'upi' | 'wallet' | 'netbanking' | 'razorpay';
  paymentStatus: 'requires_payment' | 'pending' | 'paid' | 'failed' | 'refunded';
  razorpayOrderId?: string;
  paymentId?: Schema.Types.ObjectId;
  
  // Order Status
  orderStatus: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  
  // Extras
  giftWrap: boolean;
  
  // Timestamps & status
  orderedAt: Date;
  estimatedDelivery?: Date;
  deliveredAt?: Date;
  createdAt: Date;
  updatedAt: Date;
  statusTimeline?: IStatusEvent[];
}

const OrderSchema: Schema = new Schema({
  userId: {
    type: String,
    required: [true, 'User ID is required'],
    index: true
  },
  orderNumber: {
    type: String,
    required: false, // Generated by pre-save hook
    unique: true,
    index: true
  },
  items: [{
    productId: {
      type: String,
      required: true
    },
    name: {
      type: String,
      required: true
    },
    price: {
      type: Number,
      required: true
    },
    quantity: {
      type: Number,
      required: true,
      min: 1
    },
    image: {
      type: String,
      required: true
    },
    variant: String
  }],
  subtotal: {
    type: Number,
    required: true,
    min: 0
  },
  gst: {
    type: Number,
    required: true,
    default: 0
  },
  shippingCost: {
    type: Number,
    required: true,
    default: 0
  },
  total: {
    type: Number,
    required: true,
    min: 0
  },
  deliveryAddress: {
    name: { type: String, required: true },
    line1: { type: String, required: true },
    line2: String,
    city: { type: String, required: true },
    state: { type: String, required: true },
    pincode: { type: String, required: true }
  },
  paymentMethod: {
    type: String,
    enum: ['cod', 'card', 'upi', 'wallet', 'netbanking', 'razorpay'],
    required: true
  },
  paymentStatus: {
    type: String,
    enum: ['requires_payment', 'pending', 'paid', 'failed', 'refunded'],
    default: 'pending'
  },
  razorpayOrderId: {
    type: String,
    index: true
  },
  paymentId: {
    type: Schema.Types.ObjectId,
    ref: 'Payment'
  },
  orderStatus: {
    type: String,
    enum: ['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled'],
    default: 'pending'
  },
  giftWrap: {
    type: Boolean,
    default: false
  },
  orderedAt: {
    type: Date,
    default: Date.now
  },
  estimatedDelivery: Date,
  deliveredAt: Date,
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  },
  statusTimeline: [
    {
      status: { type: String, required: true },
      note: { type: String },
      at: { type: Date, default: Date.now }
    }
  ]
}, {
  timestamps: true
});

// Generate order number before saving
OrderSchema.pre('save', async function(next) {
  if (!this.orderNumber) {
    const timestamp = Date.now().toString().slice(-8);
    const random = Math.floor(Math.random() * 10000).toString().padStart(4, '0');
    this.orderNumber = `ORD${timestamp}${random}`;
  }
  next();
});

const Order: Model<IOrder> = mongoose.models.Order || mongoose.model<IOrder>('Order', OrderSchema);

export default Order;

